### PR TITLE
Update googlemaps v4.10.0

### PR DESCRIPTION
**Pull request by giswqs**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by giswqs** [comment]
@conda-forge-admin, please rerender

**Comment by giswqs** [comment]
@david-gang @conda-forge-admin @dhirschfeld Can you please review and merge this PR? The googlemaps recipe has not been updated for over two years and the builds are no longer available on conda-forge. I need this for a downstream package. Thanks.

**Review by dhirschfeld — APPROVED** [review]
LGTM :shipit:

**Comment by dhirschfeld** [comment]
Looks good to me, but I'm not a member of @conda-forge/core so I can't actually merge.

Since it appears unmaintained and you've fixed it here, I'm sure someone from core will merge when they can find the time. It migh

**Pull request merged**
